#!/usr/bin/env python3
"""Start autonomous, center-biased frontier exploration."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("robot_clearance", default_value="0.10"),
        DeclareLaunchArgument("goal_clearance", default_value="0.15"),
        DeclareLaunchArgument("waypoint_spacing", default_value="0.75"),
        DeclareLaunchArgument("minimum_frontier_size", default_value="0.50"),
        DeclareLaunchArgument("minimum_goal_distance", default_value="1.80"),
        DeclareLaunchArgument("minimum_route_length", default_value="2.00"),
        DeclareLaunchArgument("fallback_goal_distance", default_value="0.80"),
        DeclareLaunchArgument("fallback_route_length", default_value="0.35"),
        DeclareLaunchArgument("route_horizon", default_value="10.00"),
        DeclareLaunchArgument("planning_period", default_value="2.00"),
        DeclareLaunchArgument("preview_planning_period", default_value="0.50"),
        DeclareLaunchArgument("preview_maximum_age", default_value="1.25"),
        DeclareLaunchArgument("maximum_route_poses", default_value="40"),
        DeclareLaunchArgument("clearance_weight", default_value="5.0"),
        DeclareLaunchArgument("wall_heading_radius", default_value="1.50"),
        DeclareLaunchArgument("rolling_replan_poses", default_value="4"),
        DeclareLaunchArgument("rolling_replan_distance", default_value="4.0"),
        DeclareLaunchArgument("route_extension_period", default_value="3.0"),
        DeclareLaunchArgument("information_weight", default_value="4.0"),
        DeclareLaunchArgument("frontier_bonus", default_value="6.0"),
        DeclareLaunchArgument("revisit_weight", default_value="3.0"),
        DeclareLaunchArgument("visited_radius", default_value="0.75"),
        DeclareLaunchArgument("visit_record_spacing", default_value="0.25"),
        DeclareLaunchArgument("unavoidable_transit_threshold", default_value="1.0"),
        DeclareLaunchArgument("wall_transit_distance", default_value="1.05"),
        DeclareLaunchArgument("wall_transit_weight", default_value="4.0"),
        DeclareLaunchArgument("unavoidable_route_horizon", default_value="25.0"),
        DeclareLaunchArgument("travel_weight", default_value="0.20"),
        DeclareLaunchArgument("continuity_weight", default_value="0.80"),
        DeclareLaunchArgument("forward_weight", default_value="2.0"),
        DeclareLaunchArgument("reverse_penalty", default_value="6.0"),
        DeclareLaunchArgument("frontier_lateral_penalty", default_value="0.40"),
        DeclareLaunchArgument("corridor_lookahead", default_value="6.0"),
        DeclareLaunchArgument("corridor_half_width", default_value="4.0"),
        DeclareLaunchArgument("minimum_corridor_width", default_value="1.20"),
        DeclareLaunchArgument("progress_timeout", default_value="20.0"),
        DeclareLaunchArgument("discovery_progress_timeout", default_value="30.0"),
        DeclareLaunchArgument("minimum_discovery_area_gain", default_value="1.0"),
        DeclareLaunchArgument("significant_progress", default_value="0.25"),
        DeclareLaunchArgument("stuck_radius", default_value="2.0"),
        DeclareLaunchArgument("stuck_timeout", default_value="120.0"),
        DeclareLaunchArgument("recovery_backup_distance", default_value="2.14"),
        DeclareLaunchArgument("backup_replan_attempts", default_value="2"),
        Node(
            package="create2_demo",
            executable="wandering_mapper.py",
            name="wandering_mapper",
            output="screen",
            parameters=[{
                "use_sim_time": True,
                "robot_clearance": LaunchConfiguration("robot_clearance"),
                "goal_clearance": LaunchConfiguration("goal_clearance"),
                "waypoint_spacing": LaunchConfiguration("waypoint_spacing"),
                "minimum_frontier_size": LaunchConfiguration("minimum_frontier_size"),
                "minimum_goal_distance": LaunchConfiguration("minimum_goal_distance"),
                "minimum_route_length": LaunchConfiguration("minimum_route_length"),
                "fallback_goal_distance": LaunchConfiguration("fallback_goal_distance"),
                "fallback_route_length": LaunchConfiguration("fallback_route_length"),
                "route_horizon": LaunchConfiguration("route_horizon"),
                "planning_period": LaunchConfiguration("planning_period"),
                "preview_planning_period": LaunchConfiguration("preview_planning_period"),
                "preview_maximum_age": LaunchConfiguration("preview_maximum_age"),
                "maximum_route_poses": LaunchConfiguration("maximum_route_poses"),
                "clearance_weight": LaunchConfiguration("clearance_weight"),
                "wall_heading_radius": LaunchConfiguration("wall_heading_radius"),
                "rolling_replan_poses": LaunchConfiguration("rolling_replan_poses"),
                "rolling_replan_distance": LaunchConfiguration("rolling_replan_distance"),
                "route_extension_period": LaunchConfiguration("route_extension_period"),
                "information_weight": LaunchConfiguration("information_weight"),
                "frontier_bonus": LaunchConfiguration("frontier_bonus"),
                "revisit_weight": LaunchConfiguration("revisit_weight"),
                "visited_radius": LaunchConfiguration("visited_radius"),
                "visit_record_spacing": LaunchConfiguration("visit_record_spacing"),
                "unavoidable_transit_threshold": LaunchConfiguration(
                    "unavoidable_transit_threshold"
                ),
                "wall_transit_distance": LaunchConfiguration("wall_transit_distance"),
                "wall_transit_weight": LaunchConfiguration("wall_transit_weight"),
                "unavoidable_route_horizon": LaunchConfiguration("unavoidable_route_horizon"),
                "travel_weight": LaunchConfiguration("travel_weight"),
                "continuity_weight": LaunchConfiguration("continuity_weight"),
                "forward_weight": LaunchConfiguration("forward_weight"),
                "reverse_penalty": LaunchConfiguration("reverse_penalty"),
                "frontier_lateral_penalty": LaunchConfiguration("frontier_lateral_penalty"),
                "corridor_lookahead": LaunchConfiguration("corridor_lookahead"),
                "corridor_half_width": LaunchConfiguration("corridor_half_width"),
                "minimum_corridor_width": LaunchConfiguration("minimum_corridor_width"),
                "progress_timeout": LaunchConfiguration("progress_timeout"),
                "discovery_progress_timeout": LaunchConfiguration("discovery_progress_timeout"),
                "minimum_discovery_area_gain": LaunchConfiguration("minimum_discovery_area_gain"),
                "significant_progress": LaunchConfiguration("significant_progress"),
                "stuck_radius": LaunchConfiguration("stuck_radius"),
                "stuck_timeout": LaunchConfiguration("stuck_timeout"),
                "recovery_backup_distance": LaunchConfiguration("recovery_backup_distance"),
                "backup_replan_attempts": LaunchConfiguration("backup_replan_attempts"),
            }],
        ),
    ])
